spring:
  config:
    activate:
      on-profile: common-test
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 25GB
      max-request-size: 25GB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: ${OPENAI_MODEL}
    mcp:
      server:
        protocol: streamable


jwt:
  secret: ${JWT_SECRET}

external:
  food-ntr-cpnt:
    base-url: ${FOOD_NTR_CPNT_URL}
    service-key: ${FOOD_NTR_CPNT_KEY}

  kor2-service:
    base-url: ${KOR2_SERVICE_URL}
    service-key: ${KOR2_SERVICE_KEY}

  tar-rlte-tar-service:
    base-url: ${TAR_RLTE_TAR_SERVICE_URL}
    service-key: ${TAR_RLTE_TAR_SERVICE_KEY}


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: com.planb
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
