spring:
  config:
    activate:
      on-profile: common-prod
  datasource:
    url: ${mysql_url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql_username}
    password: ${mysql_password}

  servlet:
    multipart:
      max-file-size: 25GB
      max-request-size: 25GB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: ${OPENAI_MODEL}
    mcp:
      server:
        protocol: streamable
      client:
        streamable-http:
          connections:
            planb:
              url: http://localhost:8080
              endpoint: /mcp

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: com.planb
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

